### ISSUE TITLE
Success story: Project Sunflower

### ISSUE THREAD

**Issue by daniel-j** [RobtAll/novel#2]
I found the novel package when I was looking for a way to do typesetting with LaTeX a couple of months ago. I had never used LaTeX before for anything besides playing with the book and memoir document classes. When I found novel, it was exactly what I needed for making a great looking PDF of the story. Before that, I had only considered releasing it as an ebook, edited and formatted. With novel I was able to create a PDF based on the same contents of the ebook, with both looking great. Without it, this printing would never have happened.

This is a success story-report because I've just received a test printed proof of what will be the final book. Cover pdf and book block pdf are both made with novel. I am using a local print-on-demand company. With permission from the author, I will [soon start taking orders](https://www.fimfiction.net/group/1563/project-harmonics/thread/326742/project-sunflower-book) from people who are fans of the [story](https://www.fimfiction.net/story/5170/project-sunflower) I'm printing and get them printed and shipped worldwide.

All files that make up the book (except the licensed font and the cover art) can be [found here](https://gitlab.com/djazz/project-sunflower-ebook). See `book.tex` for the main TeX file.
I use a program called [HTML to LaTeX](http://htmltolatex.sourceforge.net/) that I use to generate the TeX files for all the chapters. It's very customizable and converts HTML elements and CSS properties directly to LaTeX commands specified in `htmltolatex-config.xml`. This way, when I fix a typo for example in the ebook, the pdf can be generated including the same fix.

[PDF screenshot](https://images.imgbox.com/37/0b/Wzu4zrKJ_o.png)
You can see photos of the test print book here: https://photos.app.goo.gl/hDxrutjZHqMVhSP83
[Download PDF](https://github.com/RobtAll/novel/files/1358191/Project.Sunflower.test.print.171004.pdf)

Again, many thanks for novel! I have had a great time using it, and the documentation is fantastic! I would love to contribute somehow, but I'm not very familiar with LaTeX yet. I'm a web developer mainly.

I would put this on the wiki page of this repo, but I wasn't able to so I post this as an issue instead. Feel free to move this to a wiki page.

Contact: djazz@djazz.se

**Comment by RobtAll** [comment]
Excellent. However, if your intent is to sell the printed book for profit (I assume that is the case), then do not leave the TeX source code where others can find it. They may think that you are making it available for printing by other means.

**Comment by daniel-j** [comment]
The printing is non-profit. All costs go to the print-on-demand company, materials and shipping. I launch the crowdfunding campaign tomorrow. If someone wants to reprint it in the future, they can contact the author and use my source code.

**Comment by daniel-j** [comment]
150 copies were printed and most have been shipped and delivered. Late orders will be shipped in January. Thank you for `novel`, @RobtAll! :D
[Pile of books and other pics](https://photos.app.goo.gl/hDxrutjZHqMVhSP83)
