### ISSUE TITLE
\tocitem uses \dotfill which renders misaligned dots

### ISSUE THREAD

**Issue by daniel-j** [RobtAll/novel#7]
Screenshot of the pdf of The House on the Borderland:
![screen shot 2018-03-19 at 11 57 30](https://user-images.githubusercontent.com/1264014/37592097-f7a139c8-2b6d-11e8-83b7-5a2646c00bb8.png)

A solution is to replace `\dotfill` with `\leaders\hbox to 0.3em{\hfil.\hfil}\hfill` or something similar.

I used this in the code for a book before the `toc` environment to fix it without modifying `novel` itself:
`\renewcommand\dotfill{\leaders\hbox to 0.3em{\hfil.\hfil}\hfill}`

Result:
![screen shot 2018-03-19 at 12 08 03](https://user-images.githubusercontent.com/1264014/37592205-422751e4-2b6e-11e8-80d1-3cb8dab0b91b.png)

**Comment by RobtAll** [comment]
Ah. I had to look at that a few times, before I realized what "misaligned dots" meant. It never occurred to me that the dots needed to be aligned.

I'll look at your solution and, if I agree, will build it into the release version of 1.50 (later this week).

**Comment by RobtAll** [comment]
Done. Credited within the code.

**Comment by RobtAll** [comment]
Version 1.50 just uploaded to CTAN, will appear soon. Contains your code.
