### ISSUE TITLE
File novel-xmppacket.sty not found

### ISSUE THREAD

**Issue by daniel-j** [RobtAll/novel#8]
_novel_ version: 1.50 (March 28, 2018) (from CTAN)

In `novel-pdfx.sty` on line 329 there is this code `\input{novel-xmppacket.sty}` that tries to load a file, but the actual filename is `novel-xmppacket.clo`. Either rename the file or change the input filename.

**Comment by RobtAll** [comment]
Ah, good catch! I have both files, one in texmf, one in texmf-local. So, my own system did not flag an error, since it could find the file. Will send revision to CTAN tomorrow.

**Comment by RobtAll** [comment]
Fixed in version 1.50.1, just uploaded to CTAN. The correct extension is sty. While you wait for the update, you can copy the clo file to texmf-local, re-name it with sty extension, and update file name database. The content of the file is unchanged from earlier versions.
